# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKyxgkpR4mJxU_xLfn-nirEWBW8iOGzH
"""

import pandas as pd



df = pd.read_csv(r"/content/MTA_Daily_Ridership.csv")

df

df.shape

df.columns

df.loc[1]

df.iloc[1]

df

df[['Date','Subways: Total Estimated Ridership']]

df[df['Date']>'2024-10-29']

df[(df['Date']>'2024-10-29')&(df['Subways: % of Comparable Pre-Pandemic Day']>75)]

df.dtypes

df['Subways: % of Comparable Pre-Pandemic Day'].dtype



df['Subways: % of Comparable Pre-Pandemic Day'].astype('float')

df['Subways: % of Comparable Pre-Pandemic Day'] = df['Subways: % of Comparable Pre-Pandemic Day'].astype('float')

df

df['test']= df['Metro-North: % of Comparable Pre-Pandemic Day']/10

df





